### ISSUE TITLE
10.3.1

### ISSUE THREAD

**Issue by threeaccents** [gmitirol/qpdf-alpine#1]
Hey man thanks for the Repo! I've run into an issue with qpdf that got fixed 10.3.1. Any chance of having a release for that version?

**Comment by mplx** [comment]
as you might know [10.3.1](https://pkgs.alpinelinux.org/packages?name=qpdf) is available for edge - i guess this doesn't resolve your situation?

**Comment by threeaccents** [comment]
There are some issues with that build. The install works fine but when you actually try to run qpdf it errors out. I can't remember the exact error but when googling it does some most people run into the issue, and the common solution is to install from source.

I did end up giving up and just switched to an Ubuntu base image to not deal with the issue.

**Comment by xelan** [comment]
We've released a new version including QPDF 10.3.1. Would you like to test and provide feedback, @threeaccents?

**Comment by threeaccents** [comment]
Upgraded docker file.

Ran all staging tests and everything passed.

Thanks!

**Comment by mplx** [comment]
:)
